### PR TITLE
Create CountingBits.cpp

### LINKED ISSUE #21: Counting Bits
Given an integer n, return an array ans of length n + 1 such that for each i (0 <= i <= n), ans[i] is the number of 1's in the binary representation of i.

### PR DESCRIPTION
**Pull request by Mohit-Kukreja-2002**
Here is the solution for Counting Bits.

### CODE REVIEW

**Comment by Ishita-0112** [comment]
@Mohit-Kukreja-2002 Can you please tag the issue.

**Comment by Mohit-Kukreja-2002** [comment]
can u please guide me how to tag the issue? idk {-_-}

**Comment by Ishita-0112** [comment]
Sure! "Add a link" option is there on the top right bar. You have to select that option and add in the issue link. 

But no worries, I linked and closed the PR! Happy hacking!

**Comment by Mohit-Kukreja-2002** [comment]
thanks a lot :)

**Pull request merged**
